### ISSUE TITLE
Incorrect parsing logic with pipes and redirection operator

### ISSUE THREAD

**Issue by pravinxor** [tmiasko/shell-words#12]
```
let s = shell_words::split("ls -a|grep git");
println!("{:?}", s);
```
Prints out: `["ls", "-a|grep", "git"]`
Ideally, the output should be: `["ls", "-a", "|", "grep", "git"]`

This issue occurs on 1.1.0

**Comment by tmiasko** [comment]
The split function does not follow special token recognition rules for operators. This behaviour is intentional and documented.

**Comment by pravinxor** [comment]
Is it possible that another function such as `split_with_tokens()` can be made, which accepts an &str and an array of tokens to keep, so that these delimiters can be passed in of the crate?
Ex: `split_with_tokens("ls -a|grep git", ['|']);`

I believe it could be a helpful addition for implementing token recognition without hardcoding values within the crate

**Comment by pravinxor** [comment]
I have added this functionality on my fork and would be able to submit a PR if it is satisfactory

**Comment by tmiasko** [comment]
The crate is functionally complete; with no plans to extend it further.

The main use case is parsing of commands that require only word splitting to execute. The commands that include shell operators go beyond that, which is why they are unsupported.

Hope this clarifies the current state and purpose of the crate. 

Cheers,
Tomasz

**Comment by pravinxor** [comment]
I see, that sounds good. Thank you for your work!
